FROM python:3.12.2-bullseye

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt .

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt gunicorn

COPY . .

# ENV FLASK_APP=flaskr
ENV PYTHON_PATH=/app/flaskr

EXPOSE 5000

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "flaskr.app:app"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]